/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab2;

/**
 *
 * @author JosCongQuy
 */
public class Casio extends javax.swing.JFrame {

    private long a;
    private String pheptoan;
    boolean isEqualsFress = false;
    //  nhận biết khi người dùng nếu nhấn = thì nhận kết quả là true và ngược lại;

    /**
     * Creates new form Casio
     */
    public Casio() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtresul = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnthuong = new javax.swing.JButton();
        btnsqrt = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btntich = new javax.swing.JButton();
        btnphantram = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnhieu = new javax.swing.JButton();
        btnfaction = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnplus = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btntong = new javax.swing.JButton();
        btnketqua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("CASIO");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtresul.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtresul.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtresul)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtresul)
                .addContainerGap())
        );

        jPanel4.setLayout(new java.awt.GridLayout(4, 5, 5, 5));

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn1);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn2);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn3);

        btnthuong.setText("/");
        btnthuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthuongActionPerformed(evt);
            }
        });
        jPanel4.add(btnthuong);

        btnsqrt.setText("sqrt");
        btnsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphantramActionPerformed(evt);
            }
        });
        jPanel4.add(btnsqrt);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn4);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn5);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn6);

        btntich.setText("*");
        btntich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntichActionPerformed(evt);
            }
        });
        jPanel4.add(btntich);

        btnphantram.setText("%");
        btnphantram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphantramActionPerformed(evt);
            }
        });
        jPanel4.add(btnphantram);

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn7);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn8);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn9);

        btnhieu.setText("-");
        btnhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhieuActionPerformed(evt);
            }
        });
        jPanel4.add(btnhieu);

        btnfaction.setText("1/x");
        btnfaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphantramActionPerformed(evt);
            }
        });
        jPanel4.add(btnfaction);

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel4.add(btn0);

        btnplus.setText("+/-");
        btnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplusActionPerformed(evt);
            }
        });
        jPanel4.add(btnplus);

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC(evt);
            }
        });
        jPanel4.add(btnC);

        btntong.setText("+");
        btntong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntongActionPerformed(evt);
            }
        });
        jPanel4.add(btntong);

        btnketqua.setText("=");
        btnketqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketquaActionPerformed(evt);
            }
        });
        jPanel4.add(btnketqua);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        String s = evt.getActionCommand();
        txtresul.setText(txtresul.getText() + s);
        if (isEqualsFress)  {
             //nếu người dùng vừa nhán vào dấu bằng
            isEqualsFress = false;
             //chuyển giá trị về false
            txtresul.setText("");
           
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnthuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthuongActionPerformed
        a = Long.parseLong(txtresul.getText());
        if (a != 0) {
            pheptoan = "/";
            txtresul.setText("");
        }
    }//GEN-LAST:event_btnthuongActionPerformed

    private void btntichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntichActionPerformed
        a = Long.parseLong(txtresul.getText());
        pheptoan = "*";
        txtresul.setText("");

    }//GEN-LAST:event_btntichActionPerformed

    private void btnhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhieuActionPerformed
        a = Long.parseLong(txtresul.getText());
        pheptoan = "-";
        txtresul.setText("");

    }//GEN-LAST:event_btnhieuActionPerformed

    private void btntongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntongActionPerformed
        a = Long.parseLong(txtresul.getText());
        pheptoan = "+";
        txtresul.setText("");

    }//GEN-LAST:event_btntongActionPerformed

    private void btnketquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketquaActionPerformed
        long kq = 0;
        long b = Long.parseLong(txtresul.getText());
        if (pheptoan.length() > 0) {
            try {
                if (pheptoan.equals("-")) {
                    kq = a - b;
                    txtresul.setText(String.valueOf(kq));
                } else if (pheptoan.equals("+")) {
                    kq = a + b;
                    txtresul.setText(String.valueOf(kq));
                } else if (pheptoan.equals("*")) {
                    kq = a * b;
                    txtresul.setText(String.valueOf(kq));
                } else {
                    kq = a / b;
                    txtresul.setText(String.valueOf(kq));
                }
                pheptoan = "";
                isEqualsFress = true;
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_btnketquaActionPerformed

    private void btnC(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC
        // TODO add your handling code here:
        txtresul.setText("");
        pheptoan = "";
        isEqualsFress = false;
     
    }//GEN-LAST:event_btnC

    private void btnphantramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphantramActionPerformed
        if (txtresul.getText().equals("")) {
            return;
        }
         String s = evt.getActionCommand();
        try {
            double value = Double.parseDouble(txtresul.getText());
            if (s.equals("sqrt")) {
                value = Math.sqrt(value);
            }else if (s.equals("%")) {
                value =value/100;
            }if (s.equals("1/x")) {
                value = 1/value;
            }
            txtresul.setText(""+ value);
            isEqualsFress = true;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnphantramActionPerformed

    private void btnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplusActionPerformed
        try {
            double value = Double.parseDouble(txtresul.getText());
            value = -value;
            txtresul.setText(""+value );
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnplusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Casio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Casio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Casio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Casio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Casio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnfaction;
    private javax.swing.JButton btnhieu;
    private javax.swing.JButton btnketqua;
    private javax.swing.JButton btnphantram;
    private javax.swing.JButton btnplus;
    private javax.swing.JButton btnsqrt;
    private javax.swing.JButton btnthuong;
    private javax.swing.JButton btntich;
    private javax.swing.JButton btntong;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtresul;
    // End of variables declaration//GEN-END:variables
}
